(import-file "./examples/assertions.lisp")

## ── sort ────────────────────────────────────────────────────────────
(assert-list-eq (sort (list 3 1 2)) (list 1 2 3) "sort: list")
(assert-list-eq (sort ()) () "sort: empty list")
(assert-list-eq (sort (list 1)) (list 1) "sort: single element")
(assert-list-eq (sort (list 3 1 4 1 5 9 2 6)) (list 1 1 2 3 4 5 6 9) "sort: duplicates")
(assert-list-eq (sort (list 1.5 0.5 2.5)) (list 0.5 1.5 2.5) "sort: floats")
(let ((arr @[3 1 2]))
  (let ((result (sort arr)))
    (assert-true (array? result) "sort: array returns array")
    (assert-eq (get result 0) 1 "sort: array sorted first")
    (assert-eq (get result 1) 2 "sort: array sorted second")
    (assert-eq (get result 2) 3 "sort: array sorted third")
    (assert-true (identical? result arr) "sort: array mutated in place")))
(let ((result (sort [3 1 2])))
  (assert-true (tuple? result) "sort: tuple returns tuple")
  (assert-eq (get result 0) 1 "sort: tuple sorted first")
  (assert-eq (get result 1) 2 "sort: tuple sorted second")
  (assert-eq (get result 2) 3 "sort: tuple sorted third"))

## ── range ───────────────────────────────────────────────────────────
(let ((r (range 5)))
  (assert-true (array? r) "range: returns array")
  (assert-eq (length r) 5 "range: length")
  (assert-eq (get r 0) 0 "range: first")
  (assert-eq (get r 4) 4 "range: last"))
(let ((r (range 2 5)))
  (assert-eq (length r) 3 "range: start end length")
  (assert-eq (get r 0) 2 "range: start end first")
  (assert-eq (get r 2) 4 "range: start end last"))
(let ((r (range 0 10 3)))
  (assert-eq (length r) 4 "range: with step length")
  (assert-eq (get r 0) 0 "range: step first")
  (assert-eq (get r 1) 3 "range: step second")
  (assert-eq (get r 3) 9 "range: step last"))
(let ((r (range 5 0 -1)))
  (assert-eq (length r) 5 "range: negative step length")
  (assert-eq (get r 0) 5 "range: negative step first")
  (assert-eq (get r 4) 1 "range: negative step last"))
(let ((r (range 0)))
  (assert-true (array? r) "range: zero returns array")
  (assert-eq (length r) 0 "range: zero is empty"))
(let ((r (range 5 5)))
  (assert-eq (length r) 0 "range: start=end is empty"))
